#File generated by AI for testing my ft_magic.sh

#!/bin/bash
# create_test.sh

FILE="test"

# Créer le fichier rempli de zéros (44 octets pour avoir de la place)
dd if=/dev/zero of="$FILE" bs=1 count=44 2>/dev/null

# Écrire "42" à partir de l'octet 42 (offset 42)
printf "42" | dd of="$FILE" bs=1 seek=42 count=2 conv=notrunc 2>/dev/null
